version: "3.2"

services:
  dokuwiki:
    image: xtremxpert/rpi-dokuwiki
    ports:
      - 80
    volumes:
      - plugins:/dokuwiki/lib/plugins
      - data:/dokuwiki/data
      - conf:/dokuwiki/conf
      - tpl:/dokuwiki/lib/tpl
    restart: always
    environment:
      VIRTUAL_HOST: $VIRTUAL_HOST_NAME

volumes:
  plugins:
  data:
  conf:
  tpl:
