version: '3'

services:

  nginx:
    image: arm32v7/nginx
    container_name: nginx
    volumes:
      - conf:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"

  docker-gen:
    image: xtremxpert/rpi-docker-gen
    volumes:
      - conf:/etc/nginx/conf.d
      - tmpl:/etc/docker-gen/templates
      - /var/run/docker.sock:/tmp/docker.sock:ro
    command: -notify-sighup nginx -watch -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

volumes:
  html:
  conf:
  certs:
  tmpl:
